  
- hosts: localhost
  vars_files:
   - vars.yml
  tasks:
   - ec2_instance_facts:
      region: '{{ region }}'
      filters:
         tag:Name: Yuqi-terraform

      aws_access_key: '{{ aws_access_key }}'
      aws_secret_key: '{{ aws_secret_key }}'
     register: ec2


   - name: Add new instance to host group
     add_host:
       hostname: "{{ item.public_ip_address }}"
       groupname: product
     with_items: '{{ec2.instances}}'

   - name: Wait for SSH to come up
     wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=1000 state=started
     with_items: '{{ec2.instances}}'



- name: Configure instance
  hosts: product
  connection: ssh
  remote_user: ec2-user
  gather_facts: yes
  become: True
  become_user: root

  tasks:
   - name: get apt repo key
     rpm_key:
       key: http://packages.elastic.co/GPG-KEY-elasticsearch
       state: present

   - name: create repo file
     copy:
       dest: "/etc/yum.repos.d/elasticsearch.repo"
       content: |
         [elasticsearch]
         name=Elasticsearch repository
         baseurl=http://packages.elastic.co/elasticsearch/2.x/centos
         gpgcheck=1
         gpgkey=http://packages.elastic.co/GPG-KEY-elasticsearch
         enabled=1

   - name: install elasticsearch
     yum: name=elasticsearch state=present

   - name: elasticsearch.yml backup
     command: mv /etc/elasticsearch/elasticsearch.yml /etc/elasticsearch/elasticsearch_backup.yml

   - name: create elasticsearch.yml
     copy:
       dest: "/etc/elasticsearch/elasticsearch.yml"
       content: |
         cluster.name: yuqi-ec2-cluster
         node.name: node-1
         network.host: 0.0.0.0
         discovery.seed_hosts: ["0.0.0.0"]

   - name: start elasticsearch service
     service:
       name: elasticsearch
       state: started
